# Generated by Django 5.2.5 on 2025-11-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=255)),
                ('phone_no', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('model', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('role', models.BooleanField(default=False)),
            ],
        ),
    ]
